name: orc_hr
description: Project To manage access to main services in ORC-HR System.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:  ^0.13.4
  autocomplete_textfield: ^1.7.3
  json_annotation: ^4.4.0
  font_awesome_flutter: ^10.1.0
  connectivity: 0.4.5+3
  syncfusion_flutter_datagrid: ^20.1.47
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  syncfusion_flutter_charts: ^20.1.47+1
  intl: any
  bloc: ^8.0.3
  equatable: ^2.0.3
  auto_size_text: ^3.0.0
  multilevel_drawer: ^1.0.3
  date_time_picker: "^2.1.0"
  rxdart: ^0.27.3
  zefyr: ^0.10.0
  sliding_sheet: ^0.5.2
  flutter_typeahead: ^1.8.0
  flutter_offline: "^0.3.0"
  path_provider:
  shared_preferences: any
  url_launcher: any
  avatar_glow:
  table_calendar: ^2.2.3
  cupertino_icons: ^0.1.3
  firebase_messaging: ^11.2.12
  firebase_core: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  flutter_html: ^0.11.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo_ar.png
    - lib/assets/logo.png
    - lib/assets/up.png
    - lib/assets/down.png
    - lib/assets/identety.png
    - lib/Langs/ar.json
    - lib/Langs/en.json

